use_frameworks!

platform :ios, '8.0'

target 'duhaLib_Example' do
  pod 'duhaLib', :path => '../'

  target 'duhaLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
